schema_version: 1
name: radiomaster_boxer
device:
  name_contains: Radiomaster Boxer
channels:
  aux1:
    axis: 4
    inverted: false
    deadband: 0.0
  aux2:
    axis: 5
    inverted: false
    deadband: 0.0
  pitch:
    axis: 2
    inverted: false
    deadband: 0.0
  roll:
    axis: 1
    inverted: false
    deadband: 0.0
  throttle:
    axis: 0
    inverted: false
    deadband: 0.0
  yaw:
    axis: 3
    inverted: false
    deadband: 0.0
arm_channel: aux1
